### ISSUE TITLE
follower migration: getting "new account is not back-referencing this account" error

### ISSUE THREAD

**Issue by Maltimore** [tootsuite/mastodon#12216]
Tried to set up account migration. I set up the back-reference from the new account (maltimore@social.tchncs.de):

![image](https://user-images.githubusercontent.com/10359335/67620635-4fe03a80-f809-11e9-8305-6b151f8edaea.png)

then tried to move my followers to the new account from my old account (Maltimore@masto.themimitoof.fr):

![image](https://user-images.githubusercontent.com/10359335/67620663-8ae26e00-f809-11e9-9fa8-f4cfcaa199f3.png)

And I'm getting the "new account is not back-referencing this account" error. Note that I took care to get the characters case-sensitive-wise correct.

### Expected behaviour
Followers should've been moved.
### Actual behaviour
Followers not moved.

### Specifications
Both instances run Mastodon 3.0.1. Firefox 70 on Kubuntu 18.04.

**Comment by trwnh** [comment]
you need to set the account alias in both directions.

**Comment by Maltimore** [comment]
@trwnh that's what I did!
I now even set up an account redirect from the old account to the new account. It still does not work.

**Comment by bascht** [comment]
@Maltimore did you get this resolved in the end? I'm stuck with the same "is not back-referencing this account" error message while both old and new account have each other set as an alias now.

**Comment by Maltimore** [comment]
Yes! I got it resolved and it worked beautifully. But I've said it all in the last comment (before yours).
I still consider this a bug and think one of the maintainers should look into it.

**Comment by bascht** [comment]
@Maltimore Oooh – it just took a while for it to recognise the account alias on the other side. Now it also worked for me. There might be some caches involved.

At any rate, +1 for the UI issue here – it should list a proper "X isn't an alias of Y" error message.

**Comment by trwnh** [comment]
Accounts are cached for up to 2 days or until Update Person activity is received, so yes, it would probably be a good idea to refetch the remote account before checking for alsoKnownAs

**Comment by ccoenen** [comment]
I have been trying this for a few hours. Wording around this is not clear. Also that there's a cache involved is really not helping. Could the cache be invalidated automatically when trying to migrate?

**Comment by TheEvilSkeleton** [comment]
> @Maltimore Oooh – it just took a while for it to recognise the account alias on the other side. Now it also worked for me. There might be some caches involved.
> 
> At any rate, +1 for the UI issue here – it should list a proper "X isn't an alias of Y" error message.

I created a merge request https://github.com/tootsuite/mastodon/pull/13746. Hope they accept it.

**Comment by Maltimore** [comment]
Thanks @TheEvilSkeleton, but that's just part of the problem. This message is wrong:

![image](https://user-images.githubusercontent.com/10359335/81797216-c4ad6480-950e-11ea-9572-d0f4cdd7b0b5.png)

It says: "To move from another account to this one, first you need to create an account alias." But what I actually need to do, is to do this *on the old account* and alias the *new* account.

**Comment by TheEvilSkeleton** [comment]
> But what I actually need to do, is to do this _on the old account_ and alias the _new_ account.

Really? I thought I had to alias the new account to the old one. That's how I transferred my old account to the new one

**Comment by Maltimore** [comment]
Maybe this was a bug that was fixed in the meantime then. Or it didn't work when I tried back in October due to cache issues, and it was just a coincidence that it then worked when I set the alias in the forward-direction too. Anyways, I guess I'm going to close this issue then, given that you successfully migrated your followers yesterday.

**Comment by TheEvilSkeleton** [comment]
@Maltimore though what @trwnh said:
> you need to set the account alias in both directions.

i'm guessing that you have to do both? i don't remember if i aliased the old account to the new one though, so i think that i should clarify that too. (IMO you should also reopen the issue because it still isn't clear yet)

@trwnh do we still have to alias in both directions?

**Comment by Maltimore** [comment]
Reopened @TheEvilSkeleton, Thanks for looking into this in detail.

**Comment by Gargron** [comment]
> It says: "To move from another account to this one, first you need to create an account alias." But what I actually need to do, is to do this _on the old account_ and alias the _new_ account.

No, wrong. Create alias on *new* account pointing to the *old* account. On the *old* account, you just go straight to the "move to new account" screen and it works.

**Comment by Maltimore** [comment]
Okay, in that case the reason that it didn't work for me at first must've been caching issues. Closing again then :)

**Comment by Ethanol6** [comment]
Still getting this error. Although now it says "is not an alias of this account". On the new account I set the old account as an alias. Mastodon says "You can now initiate the move from the old account". On the old account I put in the new account and the current (old account) password and click "move followers". Been trying this for over a day, is this a usual amount of time for a cache issue to persist?

**Comment by boolysteed** [comment]
I am also seeing this error.

**Comment by NelsonMinar** [comment]
This is an old GitHub issue but I just ran into it. It looks like the caching problem is still there; I tried to migrate from a v3.5.3 server, ran into the "you need to create an alias" error, set up the alias, then tried to migrate again and still had it failed. Hoping the problem is just a cache and will fix itself eventually.

The messages are really confusing too. I got tripped up by the word "alias"; I think what's really going on is that the new account has to attest that it *wants* to receive followers from the old account but I wouldn't call that "aliasing".

**Comment by wioxjk** [comment]
Seeing this error aswell. Some users have had this issues for a couple of days.
I have asked the "source" instance if they could possibly restart their instance or something since I have no idea

**Comment by andryyy** [comment]
Same here with two v3.5.3 instances. Linked aliases on both.
