### ISSUE TITLE
Gender-neutral facepalm is missing from emojis

### ISSUE THREAD

**Issue by Cassolotl** [tootsuite/mastodon#15362]
The gender-neutral facepalm is missing from the emojis on queer.party (v3.2.1), so I assume it's missing on Mastodon generally. Or at least, it doesn't come up with the male and female facepalms when I type `:facepalm`. Could it be added?

**Comment by ThibG** [comment]
it's named :face_palm:

**Comment by Cassolotl** [comment]
Oh no, that's so inconsistent with `:man_facepalming:` and `:woman_facepalming`! 😭 

Can you make it so that `:face_palm:` comes up as an option when you type `:facep`, alongside `:man_facepalming:` and `:woman_facepalming`? At the moment it looks like this:

![Screenshot 2020-12-26 at 13 20 07](https://user-images.githubusercontent.com/6607512/103152158-198bab80-477d-11eb-9386-8e74d7965346.png)

I totally get that this is probably quite low-priority. :D

**Comment by Gargron** [comment]
The names come from an emoji dataset that’s not directly under our control

**Comment by Cassolotl** [comment]
Ahh I understand. Sad times.

**Comment by xtaran** [comment]
@Cassolotl wrote:
> The gender-neutral facepalm is missing from the emojis on queer.party (v3.2.1), so I assume it's missing on Mastodon generally. Or at least, it doesn't come up with the male and female facepalms when I type `:facepalm`.

Ran into the very same issue on https://chaos.social/@xtaran/110145726723803753 (running at version 4.1.1) today.

> Oh no, that's so inconsistent with `:man_facepalming:` and `:woman_facepalming`!

Yep. Very inconsistent. And dashes and underscores are more annoying to be typed in such shortcuts.

> Can you make it so that `:face_palm:` comes up as an option when you type `:facep`, alongside `:man_facepalming:` and `:woman_facepalming`?

Yes, please!

@Gargron wrote:
> The names come from an emoji dataset that’s not directly under our control

@Cassolotl wrote:
> **Edit:** Does the emoji dataset have an issue list where I can report this?

Ping @Gargron: Please tell us what and where the upstream project is so that we can file a bug report there.

**Comment by ClearlyClaire** [comment]
The upstream project is [emoji-mart](https://github.com/missive/emoji-mart), unfortunately we're unable to use the latest version right now because it's essentially been rewritten and would require quite a few changes on our end.

**Comment by xtaran** [comment]
> The upstream project is [emoji-mart](https://github.com/missive/emoji-mart),

Thanks a lot!

> unfortunately we're unable to use the latest version right now because it's essentially been rewritten and would require quite a few changes on our end.

Oops. So does that mean, Mastodon users won't get any potential security update from that project?

**Comment by Gargron** [comment]
Client side libraries typically do not require security updates.

**Comment by Cassolotl** [comment]
It sounds like this means there won't be any emoji updates at all for the foreseeable future?

**Comment by ClearlyClaire** [comment]
Yes and no, supporting display of new emojis is independent and less work to keep up with, but the emoji selector and autocomplete are indeed tied to emoji-mart.

I think we could also fork emoji-mart and update its emoji database, that would be a little bit of work but nothing close to updating to newer versions of the package.

**Comment by muratcorlu** [comment]
As far as I see, Mastodon already uses a non-maintained fork of emoji-mart: https://github.com/mashirozx/emoji-mart (which is [emoji-mart-lazyload](https://www.npmjs.com/package/emoji-mart-lazyload) in npm).

**Comment by viviicat** [comment]
Question: If someone were to attempt to work on getting the new version to work with Mastodon's codebase, would that be appreciated? Or is it a situation where there are too many dependencies and connections and is preferable to avoid?

**Comment by TheEssem** [comment]
I feel like it may be time to start looking at other options, emoji-mart itself appears to be unmaintained and the current versions look to be difficult to migrate to. Continuing to patch emoji-mart v3 is an option, but I feel like there's only so far we can go with that.

Maybe also worth considering rewriting the picker, especially with the amount of patching that's currently being done to emoji-mart anyways?

**Comment by SnoopJ** [comment]
Am I mistaken in saying that `emoji-mart` v3 includes at least some [functionality for specifying a custom dataset](https://www.npmjs.com/package/emoji-mart/v/3.0.1#datasets)? It seems that the more modern API has [more thoroughly decoupled data from the library](https://www.npmjs.com/package/emoji-mart?activeTab=readme#-data), where the older API seems like it may force a switchover to the `NimblePicker` component.

Maybe it's worth paying the one-time cost of migration to gain the ability to update the dataset as needed, or maybe `NimblePicker` would suffice? It isn't clear to me what (if anything) the burden would be for preparing new datasets in the format that `emoji-mart` expects in either version, however. More clarity on that might be a good way to move forward.

Mastodon is now _three_ major releases of Unicode behind and unless it plans to never move beyond Unicode 12, something's got to give.

**Comment by mjankowski** [comment]
This is ~4 years old and the actual original issue was solved almost right away by identifying a typo, more or less.

Going to close this on assumption that the core issue was resolved ... but the subsequent updates here were also useful, so I guess -- to the extent there is any narrow/actionable items to handle re: emojis/emojimart/etc ... maybe those need issues/PRs (if not existing elsewhere already?)

**Comment by trwnh** [comment]
#18609 appears to be the next closest issue?

**Comment by SnoopJ** [comment]
> maybe those [emoji problems] need issues/PRs (if not existing elsewhere already?)

Related issues also blocked by the pinned version of `emoji-mart`: #18609, #24470

**Comment by xtaran** [comment]
It is not a "typo issue" if gender-neutral and gender-flavoured emojis are using a different synta!. And it is still present 4.3.1

**Comment by mjankowski** [comment]
> IMHO the super clean (but complex and correct) solution is to ignore all underscores in emoji names at least during completion.

Yeah, something like a fuzzy finder seems appropriate here.

For whatever its worth, RE: the original requirement here of "when I type, `facep` please show me the facepunch, the man-facepalming, the woman-facepalming, and the face_palm options" - like you just observed this still does not work correctly on 4.3, but I did verify on the demo at https://missiveapp.com/open/emoji-mart that their (presumably latest) version does in fact pull all 4 options with that string ... so yes, seems like if we could sort out the upgrade path, we will solve that as a side effect.

**Comment by ChaosExAnima** [comment]
hi there! i believe this issue is fixed now that we utilize a new approach for emoji autocomplete which has `:facepa` show the neutral variant:

<img width="1150" height="612" alt="Image" src="https://github.com/user-attachments/assets/44ea2c4e-23e9-4a1a-b73a-ad878bea15d8" />

`:facep` shows the `:oncoming_fist:` emoji because it is an alias of `:facepunch:`, but i don't believe that's a problem as the expected emoji are right below that.

closing this issue, but if i missed anything please let me know.
