### ISSUE TITLE
db:migrate to 3.4.0 fails

### ISSUE THREAD

**Issue by stayinside** [tootsuite/mastodon#16273]
Running `RAILS_ENV=production bundle exec rails db:migrate` spits out the error

```
-- execute("CREATE UNIQUE INDEX CONCURRENTLY index_tags_on_name_lower_btree ON tags (lower(name)text_pattern_ops)")
rails aborted!

StandardError: An error has occurred, all later migrations canceled:
PG::DuplicateTable: ERROR: relation "index_tags_on_name_lower_btree" already exists
```

and later down

```Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR: relation "index_tags_on_name_lower_btree" already exists```

**Comment by stayinside** [comment]
Commented out the execute line in the migrate file and am running well now.

**Comment by ClearlyClaire** [comment]
Were there other things in the logs? A complete copy of the `db:migrate` logs would be helpful, especially if you ran it multiple time.

If my hunch is correct, the `index_tags_on_name_lower_btree` index exists in your database but couldn't be built and is marked as invalid (you could check that by connecting to the postgresql database and typing `\d+ tags`).

If that's the case, your workaround will only create more issues.

Now, I am not completely sure what would have caused the issue in the first place but I highly suspect that your database was already corrupted (see https://docs.joinmastodon.org/admin/troubleshooting/index-corruption/), in which case you probably want to run that script.

**Comment by stayinside** [comment]
Ran `RAILS_ENV=production bundle exec rails db:migrate:down VERSION=20210421121431` and then uncommented out the line. Strangely now I'm not getting any errors, so unsure how to get you that log.

`\d+ tags` Gives me this.

```
Indexes:
    "tags_pkey" PRIMARY KEY, btree (id)
    "index_tags_on_name_lower_btree" UNIQUE, btree (lower(name::text) text_pattern_ops)
Referenced by:
    TABLE "statuses_tags" CONSTRAINT "fk_3081861e21" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
    TABLE "featured_tags" CONSTRAINT "fk_rails_23a9055c7c" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
```

**Comment by stayinside** [comment]
Also have followed the troubleshooting link and received no errors on either of the database commands or the fix-duplicates one.

**Comment by ClearlyClaire** [comment]
ok, this is weird but at least your case is solved…

keeping that issue open in case someone else stumbles on this and we get some more info

**Comment by ClearlyClaire** [comment]
@AxelTerizaki ok I'm not quite sure what state your database is in right now, I'm afraid the index could possibly be invalid, can you check with `\d+ tags`?

**Comment by AxelTerizaki** [comment]
Indeed, the index seems invalid : 

```
Indexes:
    "index_tags_on_id" PRIMARY KEY, btree (id)
    "index_tags_on_name_lower_btree" UNIQUE, btree (lower(name::text) text_pattern_ops) INVALID
Referenced by:
    TABLE "statuses_tags" CONSTRAINT "fk_3081861e21" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
    TABLE "featured_tags" CONSTRAINT "fk_rails_23a9055c7c" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
```
How do I go fixing it? I've ran the script earlier, do I need to run it again?

**Comment by ClearlyClaire** [comment]
Try `REINDEX index_tags_on_name_lower_btree`. If it fails, stop your Mastodon instance and run the `fix-duplicates` script (you should edit `fix_duplicates` in `lib/mastodon/maintenance_cli.rb` to make it only call `deduplicate_tags!` and not the other stuff, otherwise it will run all the lengthy deduplication procedures that you most probably don't need anymore)

**Comment by AxelTerizaki** [comment]
Using the `REINDEX INDEX` command worked (no errors on postgresql's end) on the index, so I guess I'm all good?

**Comment by ClearlyClaire** [comment]
> Using the `REINDEX INDEX` command worked (no errors on postgresql's end) on the index, so I guess I'm all good?

Yup, it should be fine, now!

**Comment by ClearlyClaire** [comment]
Closing as the migration script has been fixed to be more helpful in case of database corruption. I have some ideas down the road to avoid those issues completely, but that will be for a future release.

**Comment by comzeradd** [comment]
Hi! I'm trying to upgrade from `v3.3.3` to `v3.4.0` and I'm running on the same issue.

```
SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate
```

```
Migrating to AddCaseInsensitiveBtreeIndexToTags (20210421121431)
== 20210421121431 AddCaseInsensitiveBtreeIndexToTags: migrating ===============
[strong_migrations] DANGER: No lock timeout set
-- execute("CREATE UNIQUE INDEX CONCURRENTLY index_tags_on_name_lower_btree ON tags (lower(name) text_pattern_ops)")
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "index_tags_on_name_lower_btree" already exists

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "index_tags_on_name_lower_btree" already exists

Caused by:
PG::DuplicateTable: ERROR:  relation "index_tags_on_name_lower_btree" already exists
```

While in that state, if I run `\d+ tags` on Postgres I get:

```
Indexes:
    "tags_pkey" PRIMARY KEY, btree (id)
    "index_tags_on_name_lower" UNIQUE, btree (lower(name::text))
    "index_tags_on_name_lower_btree" UNIQUE, btree (lower(name::text) text_pattern_ops)
Referenced by:
    TABLE "statuses_tags" CONSTRAINT "fk_3081861e21" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
    TABLE "account_tag_stats" CONSTRAINT "fk_rails_1fa34bab2d" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
    TABLE "featured_tags" CONSTRAINT "fk_rails_23a9055c7c" FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
```

I went through the corruption guide, but no corruption found. I also run the reduplication script but the error still persists.

**Comment by Gargron** [comment]
I’m not sure but it could be something we might have fixed in 3.5.0 so I would try checking that version out instead of 3.4.0

**Comment by comzeradd** [comment]
Thanks! I managed to make it work. It seems that mastodon services were running while I run the deduplication script. I migrated the db to the previous version, stopped the services, run the deduplication script and then everything worked fine from there. We are on `v3.5.0` now 🎉
