### ISSUE TITLE
roboto still loading when system-font pref checked

### ISSUE THREAD

**Issue by nightpool** [tootsuite/mastodon#4549]
It's not blocking the render, as far as I can tell, but it does still load, which is bad for mobile bandwidth:

![image](https://user-images.githubusercontent.com/233815/29050109-d9cd5d6c-7ba7-11e7-8d7f-f3750879a8e9.png)

(simulated 3g)

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
Are you sure that the fonts are not loaded by some extensions? If you hover the filenames it should show the full path of the script that is requesting the fonts.

**Comment by nightpool** [comment]
@sorin-davidoi yep, this test was done on a fresh profile of chrome canary

**Comment by sorin-davidoi** [comment]
Maybe @eramdam has some insights into why this is happening.

**Comment by eramdam** [comment]
@sorin-davidoi I would suspect it's caused by the fact that the font is defined on the `body` tag rather than on the `div[data-reactroot]` element, see http://github.com/tootsuite/mastodon/blob/a2aeacbfeed5dc7070c37a22bb2c4bac1a58a526/app/javascript/styles/basics.scss#L2

Back when I implemented the setting, I didn't find a way to add the `system-font` class directly on the `body` element, and I didn't want to remove that statement in fear of breaking rendering.

**Comment by connorshea** [comment]
This still seems to happen when the system font setting is enabled, I assume because things were refactored in the last year? Right now the font stylesheets are imported here: 

https://github.com/tootsuite/mastodon/blob/bf1bde5d6a8306284a0cce89eb8f492b8c9b7a67/app/javascript/styles/application.scss#L3

And this is `roboto.scss`:
https://github.com/tootsuite/mastodon/blob/bf1bde5d6a8306284a0cce89eb8f492b8c9b7a67/app/javascript/styles/fonts/roboto.scss#L1-L10

The problem, I assume(?), is that font-face will download the font no matter what as long as it's defined in the CSS, but I'm not 100% sure that's how it works.

**Comment by connorshea** [comment]
I have system fonts enabled but Roboto still loads:

<img width="1426" alt="screen shot 2018-08-17 at 11 42 34 am" src="https://user-images.githubusercontent.com/2977353/44280685-a9ff6c00-a212-11e8-9241-9060cc38092f.png">

I'm not sure why Montserrat doesn't load, it seems weird to me that it doesn't, but regardless this problem still seems to exist.
