### ISSUE TITLE
Toots disappear, leaving behind gaps in the column

### ISSUE THREAD

**Issue by monsterpit-daggertooth** [tootsuite/mastodon#5379]
*Since 2.0.0rc1*:

Sometimes, toots will disappear from a column and leave gaps that grow over time.  Toots around the gap are often repeated.

On occasion, the entire UI will *also* disappear, leaving behind a ``TypeError: this.node is undefined`` in Firefox's console. 

There are more screenshots here:  https://monsterpit.net/@daggertooth/98796561391496220

![2017-10-13 11-37-01](https://user-images.githubusercontent.com/30352165/31556960-9e00c2c6-b00c-11e7-9db6-538b9e91ae26.gif)
![screenshot 155](https://user-images.githubusercontent.com/30352165/31557088-16c382ca-b00d-11e7-9cdc-f7ac64ab059f.png)

* * * *

- [X] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by sorin-davidoi** [comment]
What version of Firefox are you using?

**Comment by monsterpit-daggertooth** [comment]
@sorin-davidoi 
I'm on 56.0.1.

**Comment by mkosler** [comment]
Happening on mastodon.social as well
![space-above-local-timeline](https://user-images.githubusercontent.com/1159095/31563908-98a1e46c-b026-11e7-8d09-2c4a3f0a4ef5.PNG)

**Comment by sorin-davidoi** [comment]
Can you confirm that the hidden toots have `opacity: 0` in the dev-tools?
![image](https://user-images.githubusercontent.com/2109702/31565767-5ac3da46-b068-11e7-8eb0-79804987035c.png)

**Comment by monsterpit-daggertooth** [comment]
@sorin-davidoi 

Yes:
![screenshot 158](https://user-images.githubusercontent.com/30352165/31566731-8e01686a-b031-11e7-953e-8eae0957291a.png)

**Comment by sorin-davidoi** [comment]
It is to be expected that toots that are not visible on screen to have `opacity: 0`. It seems that in this case some toots that are visible still have `opacity: 0` set.

I personally use Firefox 58.0a1 and I don't notice this, but it does not seem to be a Firefox-only issue since @mkosler uses another browser (from the screenshot).  @mkosler, can you tell us the browser and which version of it are you using?

**Comment by mkosler** [comment]
Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by mkosler** [comment]
I went and scrolled back to that point and there is no more gap. I remember refreshing the page and felt like it went away afterward, but that's fuzzy memory so don't take that as gospel.

![scrolled-back-no-gap](https://user-images.githubusercontent.com/1159095/31568738-b40f2bfa-b03b-11e7-9d83-f148e1f1fdbb.PNG)

**Comment by sorin-davidoi** [comment]
I stand corrected, just happened to me as well on Firefox Nightly on Android.

**Comment by mkosler** [comment]
Yeah, it seems pretty rare. I capture this last night. It's a couple of toots in a row that aren't correctly rendered.

![opacity-zero](https://user-images.githubusercontent.com/1159095/31578031-d01d7470-b0de-11e7-95c2-bc369f9cc1ba.PNG)

**Comment by nolanlawson** [comment]
I think this may be caused by https://github.com/tootsuite/mastodon/pull/5152. My hunch is that it happens on Firefox but not Chrome because in Firefox we use the `boundingClientRect` from the intersection observer, whereas in Chrome we calculate it on-demand using `getBoundingClientRect()` within a `requestIdleCallback`, meaning in the case of Firefox the rect may have changed in the interim.

Perhaps the simplest solution would just be to do `getBoundingClientRect()` in all browsers. It will use up more CPU/battery, but it's in a `requestIdleCallback()` and so shouldn't affect the UI. Plus it would normalize the behavior across all browsers.

Do we have a consistent repro for this? I'd like to know if this change will actually fix the issue.

**Comment by mkosler** [comment]
@nolanlawson but it does happen on Chrome.

**Comment by nolanlawson** [comment]
If someone could post a full stacktrace for `TypeError: this.node is undefined` that would be helpful; can't quite tell from the linked screenshots.

**Comment by monsterpit-daggertooth** [comment]
@nolanlawson 

Don't know how much it helps, but I have the unscaled version:
 
![screenshot 137](https://user-images.githubusercontent.com/30352165/31578519-7ba25596-b0e8-11e7-8373-e6c56aed3716.png)

**Comment by unarist** [comment]
`TypeError: this.node is undefined` in that screenshot should be fixed at #5312.

**Comment by nolanlawson** [comment]
Hopefully that fixes this issue… if not it may be unrelated and we may need to investigate more. So far I'm unable to reproduce…

**Comment by abochmann** [comment]
Happens to me too on 2.0.0rc2 using Vivaldi (Chromium engine). Not sure how useful this screenshot is, but I notice that the first visible toot has `<div tabindex="-1">` while the invisible toots are just wrapped in a `<div>`

![mastodon timeline hole inspector](https://user-images.githubusercontent.com/9380844/31588851-2c3d5e7c-b1f8-11e7-9d19-a80c61dff13e.png)

For me it happens when the Federated timeline is not pinned, I jump back and forth some time between posts in the unpinned pane, and then call back Federated with its button in the top left drawer header.

**Comment by mkosler** [comment]
Yup, just tested what @abochmann suggested. Navigating between different timelines (which switches the dynamic far-right column) causes them to appear on the federated timeline.

I also see that for visible toots its article > div tabindex="-1" and invisible toots its article > div

**Comment by abochmann** [comment]
I just updated my instance to b0407ec to include #5312, and the problem is still there.

**Comment by MightyPork** [comment]
Just had this happen again, with that timeout fix applied.

**Comment by nolanlawson** [comment]
In case folks are wondering, we have an IntersectionObserver listener that transforms toots into quasi-empty divs with a fixed height whenever they're scrolled out of view (this is to avoid running out of memory the further you scroll down the timeline). Apparently there is an issue where visible toots are being rendered as invisible.

If anybody can provide consistent steps to reproduce, that'd be super helpful. :)

**Comment by unarist** [comment]
I think this issue is similar case with https://github.com/tootsuite/mastodon/issues/5377#issuecomment-336717831 and I hope #5417 fixes this...

**Comment by abochmann** [comment]
Couldn't reproduce the behaviour on aec70b4 up to now.
