### ISSUE TITLE
Account deletion causes excessive Sidekiq tasks

### ISSUE THREAD

**Issue by Aldarone** [tootsuite/mastodon#5420]
When a user is suspended or deletes their account, the sidekiq `push` queue is filled with Tombstones activity. If it was an account with many many toots, it can take a while before the instance can push other activities in the fediverse, effectively locking it out of the federation until every tombstone is processed.

I suggest the creation of a new sidekiq queue of lower priority than push to deal with the tombstones.

(And I'm not saying that because WitchesTown has currently 2 million jobs (1% of the total instance activity) waiting in the queue 😇

**Comment by Gargron** [comment]
@unarist @cwebber

Instead of removing each status individually (at least over ActivityPub), we could send a Delete->Actor activity once. Mastodon >=1.6 can parse and understand that.

**Comment by unarist** [comment]
Yeah, but Delete->Actor doesn't seem appropriate for account suspension. Admins may undo suspension afterwards, but we can't send Undo->Delete or something because all relationships were deleted. Also still there are OStatus accounts.

So we need to reconsider batched removal anyway, I think.

**Comment by Gargron** [comment]
Maybe there is some way of expressing the activity "Actor deleted all activites"? But the problem would be, I have implemented Delete->Actor handling in 1.6 (first AP version) just in case we would use it later. But if we used something else, 1.6 wouldn't know how to handle it, therefore such deletes wouldn't work very well.

**Comment by Gargron** [comment]
Worth noting that *suspensions* as a state-of-account do *not* presently federate, nor account *deletions*. The content vanishes on remote server, but the remote account records keep on existing. Handling of Delete->Actor could add the benefit of fully removing the account records from remote databases. Once removed, if the original account was *restored*, it could then be re-discovered by other servers as a fresh account. This seems like a much better consequence of account restoration after suspension (since suspended account on origin would have 0 follows/followers, while on remote servers it would've kept old values - this way, it would be a blank slate on both)

**Comment by cwebber** [comment]
Note that ActivityPub does not currently express that Delete->Actor means "All of the things written by this actor are also deleted".  That might not be what all actors in the network want, and the side effect certainly specifies nothing about recursive behavior.

My preferred way that you would do this would be:

```
{"type": ["Delete", "PurgeActor"],
 "object": "https://social.example/users/foobar"}
```

This would allow it to be understood as just deleting the actor by instances that only know about Delete, and the additional recursive behavior can be understood by servers that understand that extension.

However I'm not sure Mastodon has the multi-type support stuff.  Given that, at the very least, a property should be used.

Should we talk about this in the SocialCG?  We don't have a meeting today but I'd be happy to schedule an ad-hoc one to talk about this IMO important-to-get-right topic.

**Comment by Chronister** [comment]
Just bumping to say that this is still an issue and quite important for large instances. Any mitigation would be very helpful.
