### ISSUE TITLE
PWA sometimes stops working on Android with ERR_FAILED

### ISSUE THREAD

**Issue by kvibber** [tootsuite/mastodon#7045]
On three occasions, I've had the Mastodon PWA from two instances across two devices (both Android/Chrome) suddenly stop working.  I get the general "This site can't be reached" error page, with ERR_FAILED as the error code, and a modal reporting "Can't connect to the site."

The instances affected were online at the time, and could be reached through the browser. Other instances' PWAs on the same device were not affected, and continued to work normally.

What I had to do, in every case, was uninstall the app, then log into the instance in the browser and choose "Add to Home Screen" from the browser menu to re-install the PWA.

Not sure if this detail is useful, but it happened with mastodon.social on two devices on March 28, at different times. (The second device didn't start experiencing the problem until after I'd fixed the first one.) And it happened with wandering.shop this morning, but only on one.

**Comment by kvibber** [comment]
A little more info, since this has happened again several times:

It seems to be triggered when there's a temporary connection problem - if I'm on a flaky network, or in a room where the signal strength is poor. But it's unable to recover afterward, and there's no way for me to tell it to reload.

I've force-quit the app, cleared its cache, restarted the phone, and combinations of all three. Nothing had any effect on the app's broken state.

The **only** way I've found to resolve it when the app gets into this state is to uninstall it, log back in through the browser, and manually add the app back to my home screen.

**Comment by Gargron** [comment]
Did you ever try swiping down to refresh the page?

**Comment by kvibber** [comment]
Yes, I've tried swiping down to refresh. It hasn't made a difference.

**Comment by kvibber** [comment]
It does seem to have two failure modes: One with the modal and one without. With the modal, it's not even possible to swipe to refresh, and clicking OK just closes the entire app. Without the modal, swipe is possible, but doesn't change anything.

Also, the URL it reports on the error page is sometimes <instance>/web/timelines/home, and sometimes the URL of a particular status. Right now I've got 2 instances showing the home URL with the modal.

**Comment by kvibber** [comment]
![cannot-connect](https://user-images.githubusercontent.com/6667023/38525256-740d195c-3c06-11e8-804e-f81b5f29b132.png)

Here's a screenshot - it's not very informative, which is why I didn't include one at first, but maybe it'll clarify things a little bit.

**Comment by kvibber** [comment]
Hi, here's another data point. I set up the Mastodon PWA with Firefox this time for comparison (same devices as the previous screenshot, a Samsung Android tablet), and after a few days I encountered this page when I tapped on the icon. Instead of loading the app like I was expecting, it asked me whether I wanted to open Firefox or Chrome. I chose Firefox, and it opened this error page:

> Corrupted Content Error
> 
> The site at https://mastodon.social/web/timelines/home has experienced a network protocol violation that cannot be repaired.
> 
> The page you are trying to view cannot be shown because an error in the data transmission was detected.
> 
> 1. Please contact the website owners to inform them of this problem.

I did a quick search on this and it looks like both error messages may be related to problems with service worker caching.

![corrupted-content-error](https://user-images.githubusercontent.com/6667023/38632238-f5effb18-3d70-11e8-8146-977a89954e2f.png)

**Comment by codl** [comment]
I think I've ran into the same issue and know how to reproduce it:

When logged out, then the front page and public pages load fine, but anything under /web fails with ERR_FAILED. (the web app manifest has /web/timelines/home as a starting page)

> The FetchEvent for "https://chitter.xyz/web/timelines/home" resulted in a network error response: a redirected response was used for a request whose redirect mode is not "follow".

**Comment by codl** [comment]
is this fixed by #7500?

**Comment by kvibber** [comment]
@codl Possibly. I haven't experienced the issue in a few weeks. At the time I reported it, I was seeing it every couple of days. But that fix only went into 2.4.0, right? One of the instances I use regularly is still on 2.3.3, so maybe I just haven't run into the right circumstances to trigger the bug since then.

If I do experience the problem again, I'll post a comment here, including the version that the affected instance is running.

**Comment by Gargron** [comment]
The corrupted content error was probably something caused by the load balancer while mastodon.social specifically was hosted on MaaStodon. I don't think that should be a problem anymore, and the PWA crash should be fixed by the redirects thing. Of course I believe it can still crash when there's just more stuff loaded in the DOM than the phone can keep up with, that happened to me on my old Android, but that's solved by a refresh. Closing.

**Comment by TriSysBusinessSoftware** [comment]
This is still a problem. I downloaded Jake's Super Simple Service Worker: https://github.com/jakearchibald/simple-serviceworker-tutorial and placed it on one of my HTTPS servers, added a manifest, lighthoused it, and after a bit of trial and error got it working on my Android (8.0.0) Chrome (68.0.3440.91) and added to home screen. All works fine both on and off-line however sometimes (random) when off-line, I get the attached error.
![screenshot_20180815-072909_chrome](https://user-images.githubusercontent.com/5684253/44134593-7b541718-a05d-11e8-8d8b-f4b3d74a2b85.jpg)
![image](https://user-images.githubusercontent.com/5684253/44134647-afebfe0a-a05d-11e8-8172-ccc15a62323b.png)

**Comment by phare2013** [comment]
I get the same issue on Android 8 plus only. This is interesting...it's supposed to do fine in offline mode. My is an angular PWA and fails after attempting  to launch  the app from a splashcreen(must be a default one because I did not create on in my manifest).

**Comment by codl** [comment]
@TriSysBusinessSoftware you may be on the wrong issue tracker, this is the issue tracker for Mastodon, a piece of social networking software

**Comment by schoettler** [comment]
Can confirm this issue happens intermittently on Android.

**Comment by venkatramanm** [comment]
I had the same issue. I was doing a redirect in my home screen based on some conditions. I get this error when it all happened too quickly. 
A simple timeOut solved the issue for me. Not sure why!! 
                          setTimeout( function(){
                                window.location.href = redirect_to;
                            },500);
